language: go
go_import_path: github.com/sonirico/go-fist
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: false
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
